name: mybartenderai_mobile
description: MyBartenderAI mobile application (feature-first architecture)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  custom_lint: ^0.6.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.1

flutter:
  uses-material-design: true
