 openapi: 3.0.3
 info:
   title: MyBartenderAI API
   version: 1.0.0
 paths:
   /v1/recommend:
     post:
       summary: Recommend cocktails from inventory and taste profile
+      parameters:
+        - in: header
+          name: X-Client-Request-Id
+          description: Optional client-supplied correlation id.
+          required: false
+          schema: { type: string }
       requestBody:
         required: true
         content:
           application/json:
             schema:
               type: object
               required: [inventory]
               properties:
                 inventory: { $ref: '#/components/schemas/Inventory' }
                 tasteProfile:
                   type: object
                   properties:
                     preferredFlavors: { type: array, items: { type: string } }
                     dislikedFlavors: { type: array, items: { type: string } }
                     abvRange: { type: string, example: "low|medium|high" }
       responses:
         "200":
           description: OK
+          headers:
+            X-Cache-Hit:
+              description: Indicates if upstream prompt cache was hit (telemetry; no PII).
+              schema: { type: boolean }
           content:
             application/json:
               schema:
                 type: array
                 items: { $ref: '#/components/schemas/Recommendation' }
         "400":
           description: Bad request
           content:
             application/json:
               schema: { $ref: '#/components/schemas/Error' }
         "500":
           description: Server error
           content:
             application/json:
               schema: { $ref: '#/components/schemas/Error' }
