name: Test Backend

on:
  pull_request:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-test.yml'
  push:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'apps/backend/package-lock.json'

    - name: Install dependencies
      working-directory: apps/backend
      run: npm ci

    - name: Run linter
      working-directory: apps/backend
      run: npm run lint
      continue-on-error: true

    - name: Run tests
      working-directory: apps/backend
      run: npm test
      
    - name: Build TypeScript
      working-directory: apps/backend
      run: npm run build
