name: Test Mobile App

on:
  pull_request:
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile-test.yml'
  push:
    branches: [main]
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: mobile/app
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze
      continue-on-error: true

    - name: Run tests
      run: flutter test

    - name: Check formatting
      run: dart format --set-exit-if-changed .
